# Generated by Django 4.2.7 on 2023-11-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesion',
            options={'ordering': ['numero']},
        ),
        migrations.RenameField(
            model_name='sesion',
            old_name='apellido',
            new_name='numero',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='nombre',
        ),
        migrations.AddField(
            model_name='sala',
            name='sesion',
            field=models.ManyToManyField(to='main.sesion'),
        ),
    ]
