# Generated by Django 4.2.7 on 2023-11-11 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_sesion_options_rename_apellido_sesion_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='pelicula',
        ),
        migrations.AddField(
            model_name='sesion',
            name='pelicula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pelicula'),
        ),
    ]
