# Generated by Django 4.2.7 on 2023-11-11 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_sesion_pelicula_sesion_pelicula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='sesion',
        ),
        migrations.AddField(
            model_name='sala',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sesion'),
        ),
    ]
