# Generated by Django 4.2.7 on 2023-11-16 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_pelicula_sala_alter_pelicula_sesion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='sesion',
        ),
    ]
