# Generated by Django 4.2.7 on 2023-11-16 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_pelicula_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sesion'),
        ),
    ]
