# Generated by Django 4.2.7 on 2023-11-16 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_pelicula_sesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='sesion',
        ),
        migrations.AddField(
            model_name='sesion',
            name='pelicula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pelicula'),
        ),
    ]
