# Generated by Django 4.2.7 on 2023-11-16 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_pelicula_sesion_sesion_pelicula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='sala',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sala'),
        ),
    ]
