# Generated by Django 4.2.7 on 2023-11-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_pelicula_sala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='pelicula',
        ),
        migrations.AddField(
            model_name='sesion',
            name='pelicula',
            field=models.ManyToManyField(to='main.pelicula'),
        ),
    ]
