# Generated by Django 4.2.7 on 2023-11-16 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_sesion_pelicula_sesion_pelicula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='pelicula',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='sesion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sesion'),
        ),
    ]
