# Generated by Django 4.2.7 on 2023-11-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_sesion_pelicula_pelicula_sesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='sesion',
        ),
        migrations.AddField(
            model_name='sesion',
            name='pelicula',
            field=models.ManyToManyField(to='main.pelicula'),
        ),
    ]
