# Generated by Django 4.2.7 on 2023-11-16 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_pelicula_sesion_sesion_pelicula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'ordering': ['titulo', 'sala']},
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='pelicula',
        ),
        migrations.AddField(
            model_name='sesion',
            name='pelicula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pelicula'),
        ),
    ]
