# Generated by Django 4.2.7 on 2023-11-16 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_pelicula_options_remove_sesion_pelicula_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'ordering': ['titulo', 'sala', 'sesion']},
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='pelicula',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sesion'),
        ),
    ]
