# Generated by Django 4.2.7 on 2023-11-19 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_api_pelicula_asiento_sala_asiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_pelicula',
            name='pelicula_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pelicula'),
        ),
    ]
