# Generated by Django 4.2.7 on 2023-11-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_api_pelicula_pelicula_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api_pelicula',
            name='titulo',
        ),
    ]
