# Generated by Django 4.2.7 on 2023-11-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_api_pelicula_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'ordering': ['titulo', 'sesion']},
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='sala',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='sala',
            field=models.ManyToManyField(to='main.sala'),
        ),
    ]
