# Generated by Django 4.2.7 on 2023-11-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_copia'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_pelicula',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
