# Generated by Django 4.2.7 on 2023-11-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_api_pelicula_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='categorias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
